[metadata]
name = obfuscation_detection
version = 2.4
author = Tim Blazytko
author_email = tim@blazytko.to
description = Binary Ninja plugin to identify obfuscated code and other interesting code constructs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mrphrazer/obfuscation_detection
license = GPL-2.0-or-later
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Operating System :: POSIX :: Linux

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
include = obfuscation_detection*

[options.extras_require]
test =
    pytest
